# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@1
  inputs:
    command: 'restore'
    projects: 'Azure.DevOps.Test'
    feedsToUse: 'select'
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Azure.DevOps.Test'
    arguments: '-c Release'
- task: DotNetCoreCLI@3
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release -o /app/publish'
    zipAfterPublish: false
    modifyOutputPath: false
- task: CmdLine@1
  inputs:
    script: |
      echo cd /app/publish...
      cd /app/publish
- task: CmdLine@2
  inputs:
    script: |
      echo execing...
      dotnet Mindray.CustomerCenter.API.dll
      echo this is success